<?php

namespace App\Enums\Property;

enum PropertyType: string
{
    case AI_TEMPERATURE = 'AI_TEMPERATURE';
    case AI_SYSTEM_PROMPT = 'AI_SYSTEM_PROMPT';
    case AI_PROMPT = 'AI_PROMPT';
    case PROVIDER = 'PROVIDER';
    case API_AUTH_TYPE = 'API_AUTH_TYPE';
    case OAUTH_API_AUTH_TYPE = 'OAUTH_API_AUTH_TYPE';
    case API_TYPE = 'API_TYPE';
    case RESPONSE_FORMAT = 'RESPONSE_FORMAT';
    case BASE_URL = 'BASE_URL';
    case USER_ID = 'USER_ID';
    case ACCESS_TOKEN = 'ACCESS_TOKEN';
    case CLIENT_ID = 'CLIENT_ID';
    case CLIENT_SECRET = 'CLIENT_SECRET';
    case OAUTH_TOKEN_URL = 'OAUTH_TOKEN_URL';
    case LIST_ITEM_SEARCH_PRIORITY = 'LIST_ITEM_SEARCH_PRIORITY';
    case ENDPOINT = 'ENDPOINT';
    case METHOD = 'METHOD';
    case HEADERS = 'HEADERS';
    case BODY = 'BODY';
    case POST_BODY = 'POST_BODY';
    case QUERY = 'QUERY';
    case USERNAME = 'USERNAME';
    case PASSWORD = 'PASSWORD';
    case BEARER_TOKEN = 'BEARER_TOKEN';
    case SECRET_KEY = 'SECRET_KEY';
    case TOKEN_REQUEST_AUTH_TYPE = 'TOKEN_REQUEST_AUTH_TYPE';
    case TOKEN_REQUEST_HEADERS = 'TOKEN_REQUEST_HEADERS';
    case TOKEN_REQUEST_BODY = 'TOKEN_REQUEST_BODY';
    case TOKEN_REQUEST_POST_BODY = 'TOKEN_REQUEST_POST_BODY';
    case TOKEN_REQUEST_QUERY = 'TOKEN_REQUEST_QUERY';
    case TOKEN_REQUEST_METHOD = 'TOKEN_REQUEST_METHOD';
    case TOKEN_REQUEST_USERNAME = 'TOKEN_REQUEST_USERNAME';
    case TOKEN_REQUEST_PASSWORD = 'TOKEN_REQUEST_PASSWORD';
    case TOKEN_REQUEST_TOKEN = 'TOKEN_REQUEST_TOKEN';
}
