<?php

namespace App\Repositories;

use App\Models\Category;
use App\Models\CategoryUser;
use App\Models\CategoryUserPermission;
use App\Models\Permission;
use App\Models\User;
use Illuminate\Database\Eloquent\Relations\Pivot;

class CategoryUserPermissionRepository extends BaseRepository
{
    public function __construct()
    {
        parent::__construct(CategoryUserPermission::class);
    }

    public function getModel(): CategoryUserPermission
    {
        return parent::getModel(); // TODO: Change the autogenerated stub
    }

}
