<?php

namespace App\Repositories;

use App\Models\Provider;
use App\Models\S;
use App\Models\Sr;
use App\Models\SResponseKey;
use App\Models\SrResponseKey;
use Illuminate\Database\Eloquent\Model;

class SResponseKeyRepository extends BaseRepository
{
    public function __construct()
    {
        parent::__construct(SResponseKey::class);
    }

    public function getModel(): SResponseKey
    {
        return parent::getModel();
    }

    public function findById(int $id): ?SResponseKey
    {
        return parent::findById($id); // TODO: Change the autogenerated stub
    }


    public function findServiceResponseKeysByNameBatch(S $service, array $names) {
        return $service->sResponseKey()->whereIn('name', $names)->get();
    }
    public function findServiceResponseKeysDiffByNameBatch(S $service, array $names) {
        return $service->sResponseKey()->get()->diff(SResponseKey::whereIn('name', $names)->get());
    }
    public function getServiceResponseKeyByName(S $service, string $name)
    {
        return $service->sResponseKey()->where('name', $name)->first();
    }

    public function findServiceResponseKeys(S $service) {
        return $service->sResponseKey()->get();
    }

    public function createServiceResponseKey(S $service, array $data) {
        $create = $service->sResponseKey()->create($data);
        $this->setModel($create);
        return true;
    }
    public function saveServiceResponseKey(SResponseKey $serviceResponseKey, array $data) {
        $this->setModel($serviceResponseKey);
        return $this->save($data);
    }
}
